print("welcum to kalku")
print("Enter your operands: ")
a, b = input().split()
print("Sum = " + str(int(a)+int(b)))
print("DIfference = " + str(int(a)-int(b)))
print("Product = " + str(int(a)*int(b)))
print("Divide = " + str(int(a)/int(b)))