import time
print("What's your name? ")
time.sleep(2)
print("What?")
time.sleep(2)
print("What is your name? ")
name1 = "Tony"
time.sleep(2)
print("Tony!")
time.sleep(2)
print("Fuck you, " + name1 + "!")
time.sleep(2)
name2 = "Ezekiel"
print(name1 + ": What's your name? ") 
time.sleep(2)
print("Ezekiel!")
time.sleep(2)
print(name1 + ": Fuck you, " + name2 + "!")
time.sleep(2)
print(name2 + ": Fuck you!")
time.sleep(2)
print(name1 + ": FUCK YOU!")
time.sleep(2)
print(name2 + ": Aye, you know what I did last night?")
time.sleep(2)
print(name1 + ": You better not bring my mother into this!")
time.sleep(2)
print(name2 + ": You know what I did?")
time.sleep(2)
print(name1 + ": You better not!")
time.sleep(2)
print(name2 + ": I built that fire over there...")
time.sleep(2)
print(name1 + ": OH...")
time.sleep(2)
print(name2 + ": AND I FUCKED YOUR MOTHER NEXT TO IT!")
time.sleep(2)
print(name1 + ": FUCK YOU, EZEKIEL!")
time.sleep(2)
print(name2 + ": Fuck you!")
time.sleep(2)
print(name1 + ": FUCK YOU!")
time.sleep(2)